INSERT INTO Item_Categories (name, slug) VALUES ('Standard Balls', 'standard-balls'),
	('Special Balls', 'special-balls'),
	('Healing', 'healing'),
	('Status Cures', 'status-cures'),
	('Revival', 'revival'),
	('Pp Recovery', 'pp-recovery'),
	('Vitamins', 'vitamins'),
	('Stat Boosts', 'stat-boosts'),
	('Spelunking', 'spelunking'),
	('Evolution', 'evolution'),
	('Dex Completion', 'dex-completion'),
	('Medicine', 'medicine'),
	('Picky Healing', 'picky-healing'),
	('Held Items', 'held-items'),
	('Effort Training', 'effort-training'),
	('Training', 'training'),
	('Choice', 'choice'),
	('Type Enhancement', 'type-enhancement'),
	('Species Specific', 'species-specific'),
	('Scarves', 'scarves'),
	('Bad Held Items', 'bad-held-items'),
	('All Machines', 'all-machines');
